package net.thebyrdnest.aoc.aoc2019.tests;

import net.thebyrdnest.aoc.aoc2019.Day06;
import org.junit.jupiter.api.*;

import java.util.Arrays;
import java.util.List;
import java.util.Set;

public class Day06Test {
    Day06 solver;

    @BeforeAll
    public static void setupBeforeClass() throws Exception {

    }

    @AfterAll
    public static void teardownAfterClass() throws Exception {

    }

    @BeforeEach
    public void setupBeforeEach() throws Exception {
        solver = new Day06();
    }

    @AfterEach
    public void tearDownAfterEach() throws Exception {

    }

    @Test
    public void Example1_1() throws Exception {
        String input = "COM,B\nB,C\nC,D\nD,E\nE,F\nB,G\nG,H\nD,I\nE,J\nJ,K\nK,L";
        solver.buildSolarSystem(input.split("\n"));

        Assertions.assertEquals(0, solver.getOrbitCount("COM"));
    }

    @Test
    public void Example_1_2() {
        String input = "COM,B\nB,C\nC,D\nD,E\nE,F\nB,G\nG,H\nD,I\nE,J\nJ,K\nK,L";
        solver.buildSolarSystem(input.split("\n"));

        Assertions.assertEquals(3, solver.getOrbitCount("D"));
    }

    @Test
    public void Example_1_3() {
        String input = "COM,B\nB,C\nC,D\nD,E\nE,F\nB,G\nG,H\nD,I\nE,J\nJ,K\nK,L";
        solver.buildSolarSystem(input.split("\n"));

        Assertions.assertEquals(7, solver.getOrbitCount("L"));
    }

    @Test
    public void Example_1_4() {
        String input = "COM,B\nB,C\nC,D\nD,E\nE,F\nB,G\nG,H\nD,I\nE,J\nJ,K\nK,L";
        solver.buildSolarSystem(input.split("\n"));

        Assertions.assertEquals(42, solver.getAllOrbitCount());
    }

    @Test
    public void Example_2_1() {
        String input = "COM,B\nB,C\nC,D\nD,E\nE,F\nB,G\nG,H\nD,I\nE,J\nJ,K\nK,L\nK,YOU\nI,SAN";

        solver.buildSolarSystem(input.split("\n"));
        List<String> list = solver.getOrbitalChain("YOU", "COM");
        List<String> list2 = solver.getOrbitalChain("SAN", "COM");
        String common = solver.findCommonPlanet("YOU", "SAN");

        Assertions.assertEquals(4, solver.findOrbitChangeLength("YOU", "SAN"));
    }

    @Test
    public void Problem1() throws Exception {
        solver.buildSolarSystem(myInput.split("\n"));
        //solver.listCounts();
        Assertions.assertEquals(234446, solver.getAllOrbitCount());
    }

    @Test
    public void Problem2() throws Exception {
        solver.buildSolarSystem(myInput.split("\n"));

        Assertions.assertEquals(385, solver.findOrbitChangeLength("YOU", "SAN"));
    }

    String myInput = "X9V,9CS\n" +
            "5S8,T3W\n" +
            "R5J,B4C\n" +
            "4H4,YNF\n" +
            "H9L,SDK\n" +
            "MZ1,HQ7\n" +
            "5B5,R6N\n" +
            "GQV,MXT\n" +
            "95Z,TM5\n" +
            "KQH,KLY\n" +
            "TQX,BJM\n" +
            "GW5,TK8\n" +
            "CZ4,G3X\n" +
            "GP4,D26\n" +
            "S9X,SZG\n" +
            "QW8,1L9\n" +
            "D9Z,44M\n" +
            "KP1,W54\n" +
            "77T,HVM\n" +
            "X24,LW5\n" +
            "28V,ZL4\n" +
            "ZG4,DL6\n" +
            "HXW,YX6\n" +
            "S8K,N2D\n" +
            "M3V,RHG\n" +
            "RL9,NRL\n" +
            "MWS,FLB\n" +
            "2QY,SQC\n" +
            "K2V,Z2C\n" +
            "PGQ,1FW\n" +
            "QCT,NYG\n" +
            "B84,8CT\n" +
            "ZPY,7RB\n" +
            "456,JFD\n" +
            "D2C,WXN\n" +
            "R5S,9PJ\n" +
            "H1D,LCY\n" +
            "QJR,N65\n" +
            "C6D,KKD\n" +
            "QY8,GCH\n" +
            "NGQ,CMG\n" +
            "V4H,H4L\n" +
            "2XV,R6S\n" +
            "J87,3KF\n" +
            "891,631\n" +
            "WQ8,GJZ\n" +
            "CX8,Q4L\n" +
            "P79,P4S\n" +
            "4JB,KTS\n" +
            "VV9,PPD\n" +
            "RNM,C4S\n" +
            "5W6,5NH\n" +
            "5KZ,WQ8\n" +
            "5NH,CYF\n" +
            "BV6,768\n" +
            "NT3,S2X\n" +
            "184,3SN\n" +
            "54Z,PQN\n" +
            "HPL,K24\n" +
            "TRL,PW9\n" +
            "7ZK,CDN\n" +
            "JFD,6K9\n" +
            "V6K,XL1\n" +
            "KTM,795\n" +
            "ZNY,G63\n" +
            "39Y,DJ2\n" +
            "CL8,5XP\n" +
            "YBQ,NXN\n" +
            "X62,18Z\n" +
            "3SJ,F3X\n" +
            "FSQ,D5J\n" +
            "5KZ,PGY\n" +
            "91X,BRW\n" +
            "SP3,KM5\n" +
            "HVM,91J\n" +
            "6Q6,HCT\n" +
            "6YN,HXW\n" +
            "TM7,LDX\n" +
            "CC2,FL1\n" +
            "Z7H,3ZC\n" +
            "XJW,2HY\n" +
            "5LN,5B5\n" +
            "WSB,XZL\n" +
            "474,BR8\n" +
            "JQ2,6YD\n" +
            "8LZ,4DN\n" +
            "84F,X62\n" +
            "HMS,G9D\n" +
            "Y6Y,811\n" +
            "CDL,J5Z\n" +
            "DZT,V5S\n" +
            "9D5,4N9\n" +
            "SJT,89J\n" +
            "2B3,WMC\n" +
            "KD9,9FM\n" +
            "ZLN,M24\n" +
            "M7C,HF7\n" +
            "HVB,FKY\n" +
            "VTR,3SV\n" +
            "JCT,96P\n" +
            "KM5,DBX\n" +
            "HMY,C1T\n" +
            "6P5,8J9\n" +
            "LXX,8ZF\n" +
            "LSH,SVS\n" +
            "DC3,TKV\n" +
            "NSX,VFC\n" +
            "W1H,456\n" +
            "R92,8ZV\n" +
            "66N,SCP\n" +
            "WPH,24K\n" +
            "FLB,1K6\n" +
            "C8V,5CP\n" +
            "VKH,N8D\n" +
            "QNM,4VQ\n" +
            "C57,N1W\n" +
            "869,MN5\n" +
            "NZR,6WY\n" +
            "FC5,HXY\n" +
            "YQC,RQ1\n" +
            "L2V,DWF\n" +
            "1V8,FCK\n" +
            "3WN,WYR\n" +
            "1K5,Q11\n" +
            "4JY,KL3\n" +
            "PL7,GJ8\n" +
            "4DY,869\n" +
            "XQ2,6P5\n" +
            "CV3,2WP\n" +
            "PW9,628\n" +
            "8SF,G9Y\n" +
            "WXG,QWN\n" +
            "6M6,Y2P\n" +
            "7VQ,HL2\n" +
            "8R2,BGR\n" +
            "W8Y,VCR\n" +
            "7ZB,97R\n" +
            "GSK,BRB\n" +
            "ZWK,CDC\n" +
            "K8F,W8Y\n" +
            "J9T,5WW\n" +
            "3MV,2QY\n" +
            "KDL,WJL\n" +
            "Y5J,2PK\n" +
            "XMB,7FF\n" +
            "7Q4,QHY\n" +
            "9LY,5QR\n" +
            "XCM,HGW\n" +
            "GK7,CYD\n" +
            "JMC,PSL\n" +
            "62D,HJR\n" +
            "BBC,SD8\n" +
            "BSH,8FC\n" +
            "2LX,ZF8\n" +
            "TK8,DN6\n" +
            "1FK,4V7\n" +
            "D42,TJV\n" +
            "3K5,2BD\n" +
            "H2M,QHR\n" +
            "CGS,4YS\n" +
            "8FC,G7M\n" +
            "RFZ,8HH\n" +
            "BBX,S6G\n" +
            "H6F,TL3\n" +
            "N5Q,XQ2\n" +
            "J66,BGK\n" +
            "MGZ,PWR\n" +
            "T52,QBH\n" +
            "32D,RQ4\n" +
            "RRT,7N2\n" +
            "88Y,RKT\n" +
            "TJK,7GN\n" +
            "V8D,3PJ\n" +
            "P44,K5Y\n" +
            "JZN,MJ2\n" +
            "KQB,KQF\n" +
            "6XC,K8F\n" +
            "5XP,9ZK\n" +
            "H67,JL2\n" +
            "K9Q,P5W\n" +
            "DBX,X9V\n" +
            "KNP,N42\n" +
            "PX8,9H5\n" +
            "GLC,CGZ\n" +
            "LKL,8DY\n" +
            "41B,BV6\n" +
            "1FW,WNC\n" +
            "DHD,D13\n" +
            "LLL,2R1\n" +
            "JG1,1V2\n" +
            "JQ9,7VP\n" +
            "1V2,43Z\n" +
            "PSV,M3V\n" +
            "P1F,Z33\n" +
            "LLK,LXX\n" +
            "RXJ,X3S\n" +
            "G85,SL9\n" +
            "X8F,C3V\n" +
            "G8Z,7QV\n" +
            "4DW,6KD\n" +
            "DRW,T27\n" +
            "HXY,N93\n" +
            "KJY,T8J\n" +
            "96P,P6H\n" +
            "W8K,94V\n" +
            "WTK,FGJ\n" +
            "83T,75F\n" +
            "2WP,LRL\n" +
            "PVK,LKV\n" +
            "T32,XFK\n" +
            "SGV,ZPL\n" +
            "QHR,N5M\n" +
            "J2P,BKC\n" +
            "ZKJ,P51\n" +
            "541,8KV\n" +
            "6VY,SLZ\n" +
            "7K7,KPV\n" +
            "NLD,693\n" +
            "BHP,V3X\n" +
            "48K,NCC\n" +
            "WS1,68V\n" +
            "8LW,VJP\n" +
            "68V,LK9\n" +
            "H7H,Z2Q\n" +
            "PXG,XFY\n" +
            "2TG,GL2\n" +
            "Z96,F4L\n" +
            "29D,PZF\n" +
            "G4X,D25\n" +
            "YZ8,VC8\n" +
            "35H,D1T\n" +
            "MD1,YFC\n" +
            "1Z7,S88\n" +
            "7S9,6PZ\n" +
            "5RJ,ZT2\n" +
            "1S2,CKC\n" +
            "7PV,Q5R\n" +
            "G5X,8YL\n" +
            "CS5,XKH\n" +
            "24K,2T8\n" +
            "Z4S,6FH\n" +
            "VY7,6FV\n" +
            "NYH,L9M\n" +
            "W3L,YM7\n" +
            "CH7,2DV\n" +
            "YJJ,4DL\n" +
            "2NN,1TR\n" +
            "N8D,GM6\n" +
            "97R,XYM\n" +
            "PKD,11M\n" +
            "3VF,4YC\n" +
            "1L6,PVX\n" +
            "3NL,C36\n" +
            "YTZ,K68\n" +
            "TMN,45L\n" +
            "SKW,G8Q\n" +
            "YM7,R5S\n" +
            "71J,LCP\n" +
            "N4M,FGZ\n" +
            "6PJ,JJL\n" +
            "CY3,FLY\n" +
            "DL9,Y4D\n" +
            "PN7,42F\n" +
            "Y3S,SR7\n" +
            "LDX,LP9\n" +
            "CDN,C3R\n" +
            "6XC,5YG\n" +
            "4H4,QY8\n" +
            "94V,Y3S\n" +
            "DRB,R5R\n" +
            "8DY,CDJ\n" +
            "GXX,4Y8\n" +
            "8H4,71J\n" +
            "6FH,SGQ\n" +
            "G9Y,YZM\n" +
            "MJ4,ZSQ\n" +
            "HM3,BT6\n" +
            "RS9,DZT\n" +
            "ZVZ,BCH\n" +
            "T9P,2YT\n" +
            "MG5,KPC\n" +
            "YPW,KK8\n" +
            "TPB,RP1\n" +
            "4P2,DLZ\n" +
            "8RV,9MB\n" +
            "C52,HLN\n" +
            "LF5,6N8\n" +
            "MZQ,M4Q\n" +
            "TM5,9Z7\n" +
            "K68,4QW\n" +
            "C8Z,D68\n" +
            "W54,7SW\n" +
            "QC4,YPR\n" +
            "MRH,HWJ\n" +
            "27Z,8N5\n" +
            "BGR,6FS\n" +
            "TT8,TRY\n" +
            "54N,TGZ\n" +
            "PWP,J5C\n" +
            "3NP,P4Z\n" +
            "9H7,3GL\n" +
            "CL8,P8X\n" +
            "R8C,C7R\n" +
            "LDC,3SR\n" +
            "CKW,N9P\n" +
            "VC8,2DK\n" +
            "SDV,9YB\n" +
            "PMJ,3Y9\n" +
            "KVV,4CV\n" +
            "7SL,K2R\n" +
            "JWR,GJ6\n" +
            "ZMC,HCB\n" +
            "TJV,LS6\n" +
            "2PK,ZVC\n" +
            "Q4L,81Q\n" +
            "VK3,X8F\n" +
            "ZRS,L8J\n" +
            "MB3,GBC\n" +
            "Z33,T32\n" +
            "4Z6,3CK\n" +
            "J33,G4G\n" +
            "YZR,JRR\n" +
            "3SR,33X\n" +
            "QGV,PS4\n" +
            "43Z,3L5\n" +
            "6M6,9WP\n" +
            "RRX,XHZ\n" +
            "HLN,XF5\n" +
            "P6H,SRJ\n" +
            "L1Q,V29\n" +
            "ZMW,H44\n" +
            "KJ9,14Z\n" +
            "K5K,LL1\n" +
            "2FY,KKJ\n" +
            "9NW,8S5\n" +
            "55Z,SJ7\n" +
            "JNC,NGQ\n" +
            "KKS,VRZ\n" +
            "FQ2,TMV\n" +
            "FGV,HJ2\n" +
            "8DQ,VWK\n" +
            "FKY,TBR\n" +
            "ZSQ,CDW\n" +
            "BQ9,GW5\n" +
            "5K6,GXX\n" +
            "Q32,FCC\n" +
            "WJ8,8FR\n" +
            "LJG,997\n" +
            "9Y9,F18\n" +
            "GPR,9F4\n" +
            "M9S,7ZK\n" +
            "SZG,Q7S\n" +
            "2RL,Q2L\n" +
            "3CT,M6G\n" +
            "VNF,66Y\n" +
            "HL2,MD7\n" +
            "XKH,HDD\n" +
            "298,78M\n" +
            "GCL,78R\n" +
            "71Q,XV6\n" +
            "3NL,J7V\n" +
            "LS6,3SC\n" +
            "BDF,ZPY\n" +
            "Y2P,JZ1\n" +
            "4DN,9XV\n" +
            "HDX,58Y\n" +
            "YJP,7PV\n" +
            "C8Z,GLC\n" +
            "8FR,HY1\n" +
            "HQK,V1B\n" +
            "LK9,Z11\n" +
            "Z3K,TWV\n" +
            "TBR,G6H\n" +
            "RGR,F8D\n" +
            "XBM,F8Z\n" +
            "46T,WVG\n" +
            "3QT,XGS\n" +
            "SJL,J3B\n" +
            "FLH,LBX\n" +
            "PSL,T15\n" +
            "KKJ,RRX\n" +
            "KTH,VJD\n" +
            "89J,LDC\n" +
            "33S,GLJ\n" +
            "VQ2,T25\n" +
            "5JR,8Q3\n" +
            "R2N,4MH\n" +
            "V4Z,Z3K\n" +
            "68L,VXK\n" +
            "X5M,NSN\n" +
            "HCT,KQH\n" +
            "DCG,QLB\n" +
            "HDD,BW1\n" +
            "F24,RHL\n" +
            "PPQ,9LY\n" +
            "F3G,QM4\n" +
            "4RC,F41\n" +
            "4YC,29M\n" +
            "LW5,WH9\n" +
            "ZZD,M44\n" +
            "QT4,SBD\n" +
            "5V4,GMB\n" +
            "JCJ,1ZK\n" +
            "JWR,2BC\n" +
            "WXG,T3V\n" +
            "G9Y,YPW\n" +
            "X29,WVB\n" +
            "SD8,7T2\n" +
            "LLW,GL1\n" +
            "THN,55Z\n" +
            "2P7,3Y2\n" +
            "PWK,3K1\n" +
            "SKC,T5M\n" +
            "3V1,5SZ\n" +
            "82T,T9P\n" +
            "7KZ,3K4\n" +
            "XPQ,QR8\n" +
            "7D5,KSC\n" +
            "VQ2,JZN\n" +
            "FMD,9M9\n" +
            "ZPL,ZCY\n" +
            "Q4G,WZ8\n" +
            "XVF,GZZ\n" +
            "PHZ,YJP\n" +
            "616,XPZ\n" +
            "SVW,P3X\n" +
            "33X,4NX\n" +
            "V99,K2Q\n" +
            "BDH,85T\n" +
            "3NB,TL1\n" +
            "LP9,C52\n" +
            "L9M,9SR\n" +
            "GCH,LK5\n" +
            "65Y,ZBJ\n" +
            "9WP,YGQ\n" +
            "2W4,LMN\n" +
            "QZ9,LLW\n" +
            "GMB,35Y\n" +
            "5ZT,VV9\n" +
            "34L,1FK\n" +
            "PPM,Y9X\n" +
            "6RS,3CJ\n" +
            "XC4,Q34\n" +
            "JZX,WGL\n" +
            "D1H,7VQ\n" +
            "FQ2,1F3\n" +
            "ZFF,FMD\n" +
            "F44,LWK\n" +
            "631,ZNY\n" +
            "PQN,GYH\n" +
            "FCC,J9X\n" +
            "V6Z,8NM\n" +
            "89K,2MH\n" +
            "QXX,4Z6\n" +
            "2NN,TPB\n" +
            "HBT,HHC\n" +
            "L2V,JWF\n" +
            "K2Q,8H1\n" +
            "D25,2C7\n" +
            "D4T,BXS\n" +
            "VGR,NN1\n" +
            "HKY,678\n" +
            "Q7V,9H7\n" +
            "PYC,G9B\n" +
            "TJL,KX5\n" +
            "SS6,N1C\n" +
            "VWP,RL9\n" +
            "H5W,YQ1\n" +
            "WLZ,YBZ\n" +
            "QJ5,Z7H\n" +
            "HS6,N2L\n" +
            "WN1,LFL\n" +
            "78R,QCT\n" +
            "GJ6,Z59\n" +
            "JNZ,WT2\n" +
            "MV8,H4B\n" +
            "DJ2,W3L\n" +
            "N4P,7ZB\n" +
            "LX9,S7T\n" +
            "ZRC,B39\n" +
            "QDZ,GVY\n" +
            "YCK,8Z6\n" +
            "DJN,X4N\n" +
            "NPK,3XG\n" +
            "61Q,CC2\n" +
            "P8X,XQD\n" +
            "TZB,7QH\n" +
            "LBC,55J\n" +
            "BCV,WFH\n" +
            "JJN,KP1\n" +
            "9VZ,LH4\n" +
            "811,QRX\n" +
            "5CF,DRW\n" +
            "MJH,NWX\n" +
            "5HN,XF1\n" +
            "26P,YJR\n" +
            "M4Q,YB1\n" +
            "LZB,P21\n" +
            "8B3,3G3\n" +
            "PKK,BBK\n" +
            "P16,28V\n" +
            "TM5,2B1\n" +
            "FXD,B5L\n" +
            "W5C,YW6\n" +
            "BN7,P16\n" +
            "T8K,NT7\n" +
            "XV6,DV7\n" +
            "QTM,6H4\n" +
            "1TR,DGH\n" +
            "CKN,DGF\n" +
            "Z6V,52T\n" +
            "FY9,K2V\n" +
            "HY1,KT9\n" +
            "R8H,29Q\n" +
            "2CL,YY6\n" +
            "J3B,ZMB\n" +
            "RMQ,4WR\n" +
            "L3C,BBG\n" +
            "WQ4,982\n" +
            "7RB,YT5\n" +
            "9M9,D9K\n" +
            "83F,BYF\n" +
            "ZLN,YS8\n" +
            "BR8,W8K\n" +
            "HG2,W2T\n" +
            "WG5,8HS\n" +
            "G77,1HW\n" +
            "NXN,KS4\n" +
            "PJV,D11\n" +
            "FYD,GM3\n" +
            "SDK,F8W\n" +
            "HCZ,9XC\n" +
            "VRS,9R2\n" +
            "NTS,NPC\n" +
            "7W8,LLT\n" +
            "GM6,5CZ\n" +
            "615,4SR\n" +
            "HRQ,CN6\n" +
            "GY1,JHP\n" +
            "1MV,KYC\n" +
            "T25,2K8\n" +
            "4DL,D1D\n" +
            "F7Q,74W\n" +
            "1L9,XF2\n" +
            "4KY,3NP\n" +
            "Q18,616\n" +
            "XQD,L9F\n" +
            "RCK,589\n" +
            "JCJ,9GM\n" +
            "LFD,QDB\n" +
            "NPC,JDM\n" +
            "P42,JQ2\n" +
            "CJX,RS5\n" +
            "P5F,PXG\n" +
            "79V,QKL\n" +
            "WS2,FXD\n" +
            "8M8,4LQ\n" +
            "CKJ,7R6\n" +
            "QCM,XY3\n" +
            "CYF,FJC\n" +
            "TZ8,RFZ\n" +
            "6KD,LD3\n" +
            "MFZ,RRT\n" +
            "RHS,4DY\n" +
            "XFS,J9M\n" +
            "F1H,6H3\n" +
            "TL3,BH5\n" +
            "XLH,QX9\n" +
            "VS2,61V\n" +
            "DWW,PRM\n" +
            "1ZK,8L6\n" +
            "ZW9,FM1\n" +
            "635,S4X\n" +
            "9MK,PN7\n" +
            "RZ5,Q9M\n" +
            "LKB,95Z\n" +
            "8YL,B1B\n" +
            "D8K,V6Z\n" +
            "BZ6,83T\n" +
            "6SH,4ZF\n" +
            "C8P,GTR\n" +
            "26L,XCM\n" +
            "5CZ,XJS\n" +
            "6Q2,7H4\n" +
            "2MH,H2K\n" +
            "M44,BWR\n" +
            "XL1,VT2\n" +
            "8WN,CQ2\n" +
            "FGC,MG5\n" +
            "X3Z,3K5\n" +
            "TKV,3CW\n" +
            "SD7,RF2\n" +
            "KJY,N3X\n" +
            "R5S,S62\n" +
            "C5B,Z2Z\n" +
            "QZF,M8H\n" +
            "5YH,YQC\n" +
            "S4X,N96\n" +
            "LKL,YXL\n" +
            "YPR,Q21\n" +
            "SYG,N2S\n" +
            "7R6,57J\n" +
            "6H3,71F\n" +
            "MVL,RZT\n" +
            "7CB,5YH\n" +
            "LMN,451\n" +
            "FGJ,TQX\n" +
            "24M,RMQ\n" +
            "1TR,LM9\n" +
            "1K6,1JH\n" +
            "68S,Q15\n" +
            "X77,23B\n" +
            "DG7,SVW\n" +
            "DPR,KJ9\n" +
            "BDV,ZDC\n" +
            "44W,2P7\n" +
            "VZ8,KDL\n" +
            "XMB,8B3\n" +
            "3SC,3KC\n" +
            "84L,WPR\n" +
            "6CR,6Q6\n" +
            "ZT2,N7L\n" +
            "42F,NPK\n" +
            "G9R,CS5\n" +
            "QXV,R6R\n" +
            "9ZK,QTM\n" +
            "NFP,7M7\n" +
            "ZRG,KJW\n" +
            "G63,P65\n" +
            "C7R,TCY\n" +
            "TBX,5V4\n" +
            "CYX,71M\n" +
            "D3F,7LM\n" +
            "LKP,2JL\n" +
            "CDT,7HW\n" +
            "6H4,1WM\n" +
            "51S,JKJ\n" +
            "X3P,SKW\n" +
            "628,NT3\n" +
            "7Q9,KG3\n" +
            "8KV,KVV\n" +
            "DL6,LT3\n" +
            "H44,HMS\n" +
            "T27,Q4G\n" +
            "N8F,HB4\n" +
            "CYD,W2V\n" +
            "6XM,FFL\n" +
            "8FR,PFN\n" +
            "7W8,NJW\n" +
            "2DS,FVQ\n" +
            "79G,VK3\n" +
            "LT6,93L\n" +
            "79M,1K5\n" +
            "WKK,B3Q\n" +
            "F29,1C8\n" +
            "YNF,1J7\n" +
            "2BD,1MY\n" +
            "1JH,5C5\n" +
            "2RC,FTL\n" +
            "6NW,ZXJ\n" +
            "VXP,SH8\n" +
            "TMY,9HR\n" +
            "QYP,NLD\n" +
            "PQD,WS1\n" +
            "75F,JQ4\n" +
            "R2R,ZFF\n" +
            "Z9L,VZ3\n" +
            "L9F,X5M\n" +
            "MNG,X52\n" +
            "JJL,N8F\n" +
            "JRH,BZV\n" +
            "5GX,R96\n" +
            "PZM,6L5\n" +
            "8T4,RNM\n" +
            "S62,8ZC\n" +
            "7FF,7KN\n" +
            "QBH,4F3\n" +
            "G74,Z83\n" +
            "SRJ,JRH\n" +
            "K92,CDT\n" +
            "D55,PHN\n" +
            "DZT,STB\n" +
            "G8T,ZWF\n" +
            "Z11,MD1\n" +
            "4WJ,KFX\n" +
            "XQK,NZQ\n" +
            "G6H,2S8\n" +
            "5G5,ZRG\n" +
            "JBV,LKQ\n" +
            "8CT,JHD\n" +
            "14Z,J33\n" +
            "R5R,C5N\n" +
            "K24,V95\n" +
            "GWT,C8Z\n" +
            "55J,8M8\n" +
            "9QW,W1H\n" +
            "RSB,JCT\n" +
            "WWX,Z52\n" +
            "TMY,ZRS\n" +
            "GZZ,BVB\n" +
            "2P7,8SV\n" +
            "ZQR,X7V\n" +
            "VWX,DJN\n" +
            "2H4,VJ3\n" +
            "M1P,QXX\n" +
            "2BC,P7Q\n" +
            "1G2,JG1\n" +
            "GBW,JNQ\n" +
            "YPR,8PY\n" +
            "N3Z,JSZ\n" +
            "F82,ZB1\n" +
            "SGQ,L9J\n" +
            "QRX,7S9\n" +
            "4MH,T8K\n" +
            "4SR,1YD\n" +
            "FD8,1KF\n" +
            "NYG,LKL\n" +
            "JMC,H2M\n" +
            "71Q,24M\n" +
            "N2L,SXJ\n" +
            "Z15,M5V\n" +
            "KG3,BCM\n" +
            "GJZ,TZ8\n" +
            "PKT,JJN\n" +
            "BR8,2MG\n" +
            "X5H,7WT\n" +
            "H43,14X\n" +
            "H9J,XJW\n" +
            "T6F,47R\n" +
            "BCH,69B\n" +
            "DRR,V7G\n" +
            "4LQ,RCK\n" +
            "8C1,TJK\n" +
            "FXS,K9Q\n" +
            "C8B,ZKH\n" +
            "X7V,6SD\n" +
            "4SF,9YD\n" +
            "4VF,HQS\n" +
            "Z59,K43\n" +
            "YGL,CL8\n" +
            "BQQ,FD9\n" +
            "9QY,298\n" +
            "4KN,62P\n" +
            "CB1,LXC\n" +
            "GGY,HVB\n" +
            "8PY,PMJ\n" +
            "6HP,TTN\n" +
            "3D8,M2Y\n" +
            "QCT,RZ5\n" +
            "8ZV,3CT\n" +
            "WNC,48K\n" +
            "L7Q,HG2\n" +
            "698,KTQ\n" +
            "6CV,ZKJ\n" +
            "FJ6,ZQ6\n" +
            "MKY,G8Z\n" +
            "YNF,RPC\n" +
            "MKG,LQ9\n" +
            "4SX,QDH\n" +
            "HQS,G81\n" +
            "78M,615\n" +
            "3Y9,DJH\n" +
            "P2B,VXC\n" +
            "39N,V4H\n" +
            "3CW,37T\n" +
            "KDX,MHS\n" +
            "H16,MVL\n" +
            "ZB1,QWM\n" +
            "4DD,XMM\n" +
            "664,RX8\n" +
            "BN4,VWP\n" +
            "3SV,4BR\n" +
            "HF7,2HW\n" +
            "N4S,1G2\n" +
            "JMJ,5BB\n" +
            "J6W,TXW\n" +
            "8Z4,ZGQ\n" +
            "1TJ,CMP\n" +
            "Q5F,D9Z\n" +
            "4WR,7KZ\n" +
            "VZ8,WQ4\n" +
            "7KY,47S\n" +
            "L8J,4H4\n" +
            "X1T,YVS\n" +
            "45Q,ST2\n" +
            "ZMW,YNK\n" +
            "VRK,T52\n" +
            "MHS,1GH\n" +
            "QCM,VG6\n" +
            "G8Q,FLZ\n" +
            "LCY,Z62\n" +
            "FM1,WLZ\n" +
            "RYB,5S8\n" +
            "CGZ,S8K\n" +
            "VG6,YR1\n" +
            "474,G26\n" +
            "BX9,SGH\n" +
            "F8W,DHD\n" +
            "4QM,G8T\n" +
            "PD9,NMT\n" +
            "KL6,CNY\n" +
            "MW4,C1K\n" +
            "TT8,SMX\n" +
            "4YS,3NN\n" +
            "7VP,1H3\n" +
            "YQC,9KC\n" +
            "TBX,ZVW\n" +
            "CDB,Y2K\n" +
            "PSV,1TP\n" +
            "Q7J,X3Z\n" +
            "COM,YKL\n" +
            "6YD,LXH\n" +
            "RP1,XBM\n" +
            "J9M,PHZ\n" +
            "M8H,71Z\n" +
            "MQ5,7SL\n" +
            "NH2,DC3\n" +
            "696,BQ9\n" +
            "VG6,MW4\n" +
            "YXL,FTZ\n" +
            "C35,7MJ\n" +
            "N65,769\n" +
            "VTV,3XR\n" +
            "LM9,Q92\n" +
            "ZSQ,Q73\n" +
            "HXY,LHP\n" +
            "V29,ZDN\n" +
            "35Y,4P2\n" +
            "5T2,BG6\n" +
            "WZZ,VTV\n" +
            "X24,WTK\n" +
            "P42,2X5\n" +
            "XMM,FQN\n" +
            "3NN,NYW\n" +
            "Q2D,3NL\n" +
            "7KN,VMX\n" +
            "5GK,JL4\n" +
            "Z9L,2DX\n" +
            "LXJ,H16\n" +
            "5Q4,KKV\n" +
            "BG6,PX8\n" +
            "X3P,5T2\n" +
            "37T,3LR\n" +
            "TVY,69M\n" +
            "V5Y,XZ2\n" +
            "B4C,Y88\n" +
            "6TJ,CY3\n" +
            "QLB,L9T\n" +
            "JVY,ZM9\n" +
            "VSK,XQM\n" +
            "Q4G,V6P\n" +
            "944,PTS\n" +
            "MR2,TWS\n" +
            "QP2,PZT\n" +
            "58Y,QW8\n" +
            "SZG,VXP\n" +
            "7GN,5RN\n" +
            "XL1,G9R\n" +
            "NRW,GSZ\n" +
            "YZM,D2C\n" +
            "6DW,84J\n" +
            "HDR,9QY\n" +
            "SY9,JHG\n" +
            "T1D,JPB\n" +
            "B1X,VGR\n" +
            "JHP,5YY\n" +
            "LZ4,QCH\n" +
            "G4G,CBD\n" +
            "WH9,KJY\n" +
            "STB,2L8\n" +
            "HQL,CRY\n" +
            "C1T,N4S\n" +
            "PFN,GRS\n" +
            "VJD,KNL\n" +
            "4VQ,JVY\n" +
            "TF5,P79\n" +
            "LT3,BHP\n" +
            "ZHF,W5C\n" +
            "PPM,7Q2\n" +
            "1KF,4KY\n" +
            "QKL,D9T\n" +
            "1M4,R9S\n" +
            "FXD,TCG\n" +
            "YR1,V84\n" +
            "QCH,PGQ\n" +
            "SH8,15Y\n" +
            "BCR,T2M\n" +
            "GJ8,6RS\n" +
            "PZ5,GS8\n" +
            "PW9,696\n" +
            "99H,14T\n" +
            "BGK,TZB\n" +
            "5DX,P6W\n" +
            "C36,455\n" +
            "9XV,DRR\n" +
            "L43,C4G\n" +
            "H4L,CKN\n" +
            "Z83,XMB\n" +
            "8ZF,2FY\n" +
            "2X5,183\n" +
            "LKQ,YBQ\n" +
            "1N4,DL9\n" +
            "TWV,26L\n" +
            "D68,8RR\n" +
            "V5S,7Q9\n" +
            "6PJ,8RV\n" +
            "SXJ,61Q\n" +
            "FZW,N3Z\n" +
            "LH4,QGV\n" +
            "GSZ,2GF\n" +
            "V3X,3Q3\n" +
            "Q9M,39Y\n" +
            "5SZ,Y5J\n" +
            "PX4,SZQ\n" +
            "KX5,SGW\n" +
            "WVB,QS6\n" +
            "CWJ,8LW\n" +
            "39K,GY4\n" +
            "ZRM,PLK\n" +
            "K1S,RCQ\n" +
            "4F3,D1H\n" +
            "LXC,V2N\n" +
            "M6G,MB3\n" +
            "Q11,64X\n" +
            "GYH,D2M\n" +
            "1H3,VP6\n" +
            "JQ4,7K7\n" +
            "WZ8,WKK\n" +
            "BNR,1N4\n" +
            "74S,H5W\n" +
            "YS8,Z4S\n" +
            "B5L,2MZ\n" +
            "TNS,MWS\n" +
            "WQV,RWH\n" +
            "VWK,X66\n" +
            "WYR,BNR\n" +
            "T3Y,F82\n" +
            "FTF,VWX\n" +
            "VCR,X68\n" +
            "CDJ,GK7\n" +
            "TZZ,SF9\n" +
            "W2V,YZ8\n" +
            "VFC,JWR\n" +
            "MPG,BTS\n" +
            "7LM,77T\n" +
            "6FV,7L9\n" +
            "R6S,ZX1\n" +
            "HMH,NTN\n" +
            "PV4,S8Z\n" +
            "P3X,PPM\n" +
            "RQ4,LVQ\n" +
            "S2X,5DN\n" +
            "XXY,8LR\n" +
            "2GF,6XC\n" +
            "CW7,F6M\n" +
            "SS6,JCJ\n" +
            "ZF8,4RC\n" +
            "LL1,S9X\n" +
            "RCQ,SJT\n" +
            "ZL4,P5F\n" +
            "TRG,JMJ\n" +
            "6VJ,1RH\n" +
            "S78,CWG\n" +
            "2YT,R8H\n" +
            "9NP,35H\n" +
            "TSQ,KD9\n" +
            "MRJ,C7L\n" +
            "KB8,LD9\n" +
            "ZDT,SDV\n" +
            "FJ2,T3R\n" +
            "TFS,944\n" +
            "4VF,2W8\n" +
            "BCM,NT4\n" +
            "9RV,P44\n" +
            "69C,D1X\n" +
            "CKC,5JD\n" +
            "ZM9,BN4\n" +
            "RWR,GKJ\n" +
            "K2W,K79\n" +
            "1S9,1DP\n" +
            "B98,BN7\n" +
            "9XC,VDR\n" +
            "D9T,HH2\n" +
            "NJG,MNG\n" +
            "T5B,GVN\n" +
            "QM4,G39\n" +
            "V95,5KQ\n" +
            "WJX,754\n" +
            "LK5,LNH\n" +
            "GMY,5BQ\n" +
            "N3N,GCW\n" +
            "HJR,VMJ\n" +
            "RS5,KTV\n" +
            "PHN,TPD\n" +
            "DNW,V8D\n" +
            "BDF,JQ9\n" +
            "PV4,XVF\n" +
            "RGX,QGB\n" +
            "5DJ,PD4\n" +
            "1XG,1QT\n" +
            "KKD,1JN\n" +
            "PVK,RKN\n" +
            "693,TNW\n" +
            "SF9,FDZ\n" +
            "1JN,WKR\n" +
            "GCW,FRV\n" +
            "DR9,MPM\n" +
            "9GM,BDV\n" +
            "431,248\n" +
            "QCT,5DC\n" +
            "PWP,1BL\n" +
            "7QV,5DX\n" +
            "DJH,G77\n" +
            "982,DNW\n" +
            "HQ7,TMN\n" +
            "7N2,99H\n" +
            "2H8,CYX\n" +
            "SD7,ZVF\n" +
            "3K1,R47\n" +
            "CMP,TT8\n" +
            "XZJ,RS9\n" +
            "LBX,C35\n" +
            "84J,83G\n" +
            "GYZ,68P\n" +
            "CNY,JNZ\n" +
            "MGZ,XPV\n" +
            "FLY,ZTD\n" +
            "3NP,P3D\n" +
            "9LC,1FJ\n" +
            "9Z7,QZF\n" +
            "2RC,PQ4\n" +
            "KTQ,RWR\n" +
            "3Y2,3NF\n" +
            "WWC,3D8\n" +
            "XF1,5RJ\n" +
            "LNH,HCJ\n" +
            "PQ4,R5J\n" +
            "YMC,V4Z\n" +
            "KYC,DCG\n" +
            "8VJ,9VZ\n" +
            "F7Q,CW7\n" +
            "M2Y,YGL\n" +
            "F8Z,6CR\n" +
            "49Y,ZHF\n" +
            "7LH,PMC\n" +
            "KTV,ZQR\n" +
            "TCG,CMC\n" +
            "8RR,FGV\n" +
            "3CK,NZC\n" +
            "Z52,Q18\n" +
            "2QF,SKC\n" +
            "G7M,1WN\n" +
            "L9T,79V\n" +
            "WPR,BDF\n" +
            "MZY,Q5F\n" +
            "TWS,WZH\n" +
            "TCM,TLF\n" +
            "795,GYZ\n" +
            "F6M,SVN\n" +
            "B3X,X3P\n" +
            "CMG,X24\n" +
            "K2K,BSH\n" +
            "XTL,PXR\n" +
            "NN1,1MV\n" +
            "QHN,MGZ\n" +
            "BRW,ZW9\n" +
            "TT4,CB1\n" +
            "85V,69C\n" +
            "YJR,4KN\n" +
            "5CP,MZQ\n" +
            "997,ZQQ\n" +
            "3W9,K1J\n" +
            "DQN,CV3\n" +
            "BT6,SWK\n" +
            "P4S,WJX\n" +
            "S6G,KRF\n" +
            "L9J,MJ5\n" +
            "W1H,W7N\n" +
            "3KF,26P\n" +
            "5WW,HKY\n" +
            "C6N,VYL\n" +
            "WZ8,B98\n" +
            "D7C,H7H\n" +
            "SZQ,FTJ\n" +
            "1FJ,X5H\n" +
            "FQN,BDH\n" +
            "ZFF,RHS\n" +
            "YS8,D9B\n" +
            "YX6,WXG\n" +
            "GXX,6Q2\n" +
            "PGD,SSM\n" +
            "CDT,CKW\n" +
            "2W8,2W4\n" +
            "5DJ,JB9\n" +
            "1TZ,H9L\n" +
            "YKL,6QX\n" +
            "YNL,R2R\n" +
            "3KL,9MK\n" +
            "3CJ,3VF\n" +
            "JHG,RQT\n" +
            "TBR,ZQF\n" +
            "XYM,K5Q\n" +
            "12H,TQH\n" +
            "VXK,D4T\n" +
            "BZV,Z4F\n" +
            "4BR,16M\n" +
            "9D4,T6F\n" +
            "7X1,4DD\n" +
            "H39,HQL\n" +
            "8MP,67J\n" +
            "GB8,CWJ\n" +
            "N9P,PZX\n" +
            "BH5,431\n" +
            "VMX,FM8\n" +
            "JNQ,D5P\n" +
            "BGK,1P2\n" +
            "8B3,WJF\n" +
            "GM3,FJ6\n" +
            "RX8,TFX\n" +
            "29Q,91X\n" +
            "QZ2,TCM\n" +
            "T8J,474\n" +
            "ZC7,B3F\n" +
            "79F,44W\n" +
            "64X,ZWK\n" +
            "LRL,XLH\n" +
            "ZQ6,XKN\n" +
            "D96,CX8\n" +
            "2QF,964\n" +
            "MJ2,YMC\n" +
            "TPD,WJ8\n" +
            "Z2H,QJR\n" +
            "4ZQ,65N\n" +
            "JL6,HBT\n" +
            "C4G,33G\n" +
            "RXJ,4SF\n" +
            "M24,GPR\n" +
            "3XG,DDD\n" +
            "VJP,ZVZ\n" +
            "7T2,BFR\n" +
            "C4H,J6Y\n" +
            "9BZ,1XG\n" +
            "S8H,YZ6\n" +
            "SRJ,1L6\n" +
            "7M7,8SN\n" +
            "PQ4,HYL\n" +
            "QML,6SH\n" +
            "S93,7C8\n" +
            "34L,3KL\n" +
            "Q2P,T7C\n" +
            "TNW,TRF\n" +
            "1J7,KND\n" +
            "YNK,CS3\n" +
            "KK8,J2P\n" +
            "D9K,K23\n" +
            "C3V,4JB\n" +
            "YM4,KD1\n" +
            "QBH,PZM\n" +
            "5CL,CZ4\n" +
            "TRY,2B3\n" +
            "PRM,54N\n" +
            "GB8,DH4\n" +
            "811,2CL\n" +
            "N16,7D5\n" +
            "CSK,PW6\n" +
            "45L,MRJ\n" +
            "57J,8R2\n" +
            "JB9,LF5\n" +
            "P6W,8C1\n" +
            "ZXJ,KDX\n" +
            "JHD,2XV\n" +
            "K1J,TZZ\n" +
            "1F3,2BY\n" +
            "K79,2H8\n" +
            "QXX,QZ9\n" +
            "C5G,1M9\n" +
            "JPX,GY1\n" +
            "Y7F,39K\n" +
            "X1T,2H4\n" +
            "T6F,G5X\n" +
            "DCQ,WQV\n" +
            "HL2,PWP\n" +
            "F18,6DW\n" +
            "2K8,6TJ\n" +
            "QGB,B3H\n" +
            "69B,ZMW\n" +
            "C4H,635\n" +
            "1RH,KDK\n" +
            "ZVZ,7WL\n" +
            "3YX,QKM\n" +
            "QDH,KPM\n" +
            "BKC,WN1\n" +
            "6L5,THN\n" +
            "5TL,SJL\n" +
            "W86,TMY\n" +
            "Z4F,97V\n" +
            "YBZ,J9T\n" +
            "4Y8,PVK\n" +
            "HPK,PSV\n" +
            "9MB,D3F\n" +
            "TSH,32D\n" +
            "XGG,BQQ\n" +
            "NYW,1G1\n" +
            "QX9,1S3\n" +
            "DN6,QZ2\n" +
            "F8T,PWK\n" +
            "P5W,FYD\n" +
            "3D8,9NP\n" +
            "GTR,MKY\n" +
            "1WM,C8B\n" +
            "QR8,TRL\n" +
            "3N5,CQM\n" +
            "VMJ,WSQ\n" +
            "SP4,9D4\n" +
            "G9D,667\n" +
            "X66,RYB\n" +
            "JL4,YTZ\n" +
            "15Y,GQV\n" +
            "RGP,5PF\n" +
            "BBK,6YP\n" +
            "VRZ,ZWL\n" +
            "H9M,1BT\n" +
            "B3Q,WB6\n" +
            "BX1,6CV\n" +
            "Y2K,N3N\n" +
            "T47,SYG\n" +
            "978,Y6C\n" +
            "6YP,W2H\n" +
            "14X,4ZQ\n" +
            "8S5,5HT\n" +
            "T7C,QDZ\n" +
            "QHP,9DC\n" +
            "2MG,N16\n" +
            "J5C,4CK\n" +
            "LW5,62D\n" +
            "WVG,SRD\n" +
            "8Q3,83F\n" +
            "26D,BBC\n" +
            "WKR,WG5\n" +
            "DDD,5ND\n" +
            "ZWL,D6G\n" +
            "2DK,SP4\n" +
            "4LH,LSN\n" +
            "VYL,7TF\n" +
            "2R1,5LX\n" +
            "16M,5Q4\n" +
            "WCM,X77\n" +
            "SBD,Y63\n" +
            "V84,8H4\n" +
            "GL1,DQN\n" +
            "KFX,M1P\n" +
            "PLK,XC4\n" +
            "5QG,TJL\n" +
            "2WR,HLB\n" +
            "KKV,SBY\n" +
            "5LX,BX9\n" +
            "DSQ,9QT\n" +
            "HH2,8SF\n" +
            "3L5,46T\n" +
            "2T8,XFS\n" +
            "RQ1,27Z\n" +
            "3NF,2RL\n" +
            "8HS,F29\n" +
            "1FC,PKT\n" +
            "Y63,QYP\n" +
            "5FG,ZLN\n" +
            "Z2Q,RW8\n" +
            "2S8,P56\n" +
            "C7M,891\n" +
            "JYY,ZRC\n" +
            "9SS,C8V\n" +
            "MJ4,FZW\n" +
            "M66,PPQ\n" +
            "TLF,VRS\n" +
            "H79,T1D\n" +
            "5P5,WCM\n" +
            "JCD,3MV\n" +
            "795,V6K\n" +
            "Q92,XZJ\n" +
            "93L,P42\n" +
            "XQM,LLK\n" +
            "N42,GMY\n" +
            "FD9,32Y\n" +
            "QLH,3NB\n" +
            "8N5,1Q4\n" +
            "J9X,L43\n" +
            "8ZF,MZY\n" +
            "D11,KTH\n" +
            "YLM,GH1\n" +
            "4NX,ZDT\n" +
            "958,L2V\n" +
            "ZSL,K5K\n" +
            "Y6C,9ZM\n" +
            "PWR,C1J\n" +
            "CSK,QYB\n" +
            "JWF,W86\n" +
            "9F4,MV8\n" +
            "SJT,9D5\n" +
            "V1F,Q7J\n" +
            "8SP,16X\n" +
            "TCY,BF8\n" +
            "T5M,TT4\n" +
            "91J,HB7\n" +
            "1G1,K4X\n" +
            "CWG,PZ5\n" +
            "WXN,NBJ\n" +
            "F1V,ZRM\n" +
            "ZX1,X1T\n" +
            "GL2,VSK\n" +
            "FPM,RGR\n" +
            "4CV,5LN\n" +
            "8ZC,VTR\n" +
            "7TF,HQK\n" +
            "5YY,8DG\n" +
            "9DC,H79\n" +
            "Y9X,5TX\n" +
            "LT6,3YX\n" +
            "GFJ,Z6V\n" +
            "CMP,S93\n" +
            "65N,X33\n" +
            "D9B,S78\n" +
            "3PJ,3WJ\n" +
            "WSQ,ZC7\n" +
            "9YD,MZ1\n" +
            "8H1,NRW\n" +
            "YB1,L3C\n" +
            "STC,LXJ\n" +
            "G39,RR3\n" +
            "9HR,GBW\n" +
            "B3F,9SJ\n" +
            "8G8,9NW\n" +
            "6CP,VKN\n" +
            "KRF,8LZ\n" +
            "2HY,R8Y\n" +
            "WB6,C4H\n" +
            "CQ2,664\n" +
            "3WN,6YN\n" +
            "YW6,XPQ\n" +
            "768,978\n" +
            "D4P,9QW\n" +
            "KQ5,BCV\n" +
            "7MZ,XW1\n" +
            "7WL,C6H\n" +
            "67J,NTS\n" +
            "FGC,F27\n" +
            "ZSZ,65S\n" +
            "7WT,B17\n" +
            "P44,5GK\n" +
            "KS4,2NN\n" +
            "1P2,GSK\n" +
            "KTS,T47\n" +
            "5TX,L7Q\n" +
            "WT2,L3D\n" +
            "5YG,SG2\n" +
            "TS4,LT6\n" +
            "6PZ,KKS\n" +
            "BW1,5ZT\n" +
            "PW6,F1V\n" +
            "1MY,5TS\n" +
            "ZDN,1S2\n" +
            "4B6,9XP\n" +
            "CV3,3LM\n" +
            "9QV,Y6Y\n" +
            "74Y,QP2\n" +
            "SLZ,KQB\n" +
            "85Z,R8C\n" +
            "9GQ,C6N\n" +
            "BF8,29Z\n" +
            "HB7,D4P\n" +
            "PZT,5KZ\n" +
            "V8D,8DQ\n" +
            "XW1,4LH\n" +
            "9CG,85Z\n" +
            "B1J,MPG\n" +
            "71Z,PKD\n" +
            "1KF,J66\n" +
            "KPM,1ZD\n" +
            "1BL,MKG\n" +
            "1YD,3N5\n" +
            "27M,XXY\n" +
            "62D,YCK\n" +
            "K8B,GB8\n" +
            "RQD,DM6\n" +
            "BJM,TS4\n" +
            "698,TVY\n" +
            "7MJ,2RC\n" +
            "23B,CKJ\n" +
            "Q15,M66\n" +
            "B1D,PD9\n" +
            "Q5F,QT4\n" +
            "5JF,S4R\n" +
            "DDQ,6HR\n" +
            "2HW,8X5\n" +
            "N93,WSB\n" +
            "FFL,VRK\n" +
            "C7L,R17\n" +
            "9NZ,2LX\n" +
            "BTY,CWF\n" +
            "18Z,9BZ\n" +
            "R17,ZG4\n" +
            "2L8,797\n" +
            "FTJ,JZX\n" +
            "M5V,7X1\n" +
            "TRL,J29\n" +
            "5NF,VS2\n" +
            "4M3,ZFX\n" +
            "PD4,6M6\n" +
            "GWX,SLR\n" +
            "SVN,7Q4\n" +
            "KD1,JYY\n" +
            "6QX,FD8\n" +
            "V6P,MJ4\n" +
            "4QM,H43\n" +
            "Z11,24X\n" +
            "RVD,51S\n" +
            "NBJ,62G\n" +
            "HJ2,LX9\n" +
            "93G,YJJ\n" +
            "K4X,J87\n" +
            "SMX,H1D\n" +
            "C57,JN6\n" +
            "4MR,6VY\n" +
            "LBC,CH7\n" +
            "KND,ZSL\n" +
            "Y5W,Q2D\n" +
            "Z2Z,284\n" +
            "G26,SY9\n" +
            "85T,QHN\n" +
            "YZY,8PW\n" +
            "4ZF,SP3\n" +
            "ZBJ,8VJ\n" +
            "N1W,H6F\n" +
            "RSQ,QC4\n" +
            "9QT,M9S\n" +
            "PZN,JRW\n" +
            "4P2,6PJ\n" +
            "62P,L26\n" +
            "T15,P27\n" +
            "F4L,FGC\n" +
            "HCZ,FC5\n" +
            "T3V,N2B\n" +
            "P7Q,MQ5\n" +
            "FM8,SS6\n" +
            "XFK,5JF\n" +
            "VMX,LZB\n" +
            "KPR,Z6B\n" +
            "RS5,DWW\n" +
            "MBY,YOU\n" +
            "W7N,PJV\n" +
            "2DX,JL6\n" +
            "HCJ,1K9\n" +
            "16X,BF7\n" +
            "FCK,MJH\n" +
            "J16,6VJ\n" +
            "2B1,R2N\n" +
            "T3R,V5Y\n" +
            "ST2,HFS\n" +
            "6K9,WWC\n" +
            "2MZ,K2W\n" +
            "M8Q,QXV\n" +
            "LKS,NYH\n" +
            "8LR,N5Q\n" +
            "YQH,GCL\n" +
            "ZMB,DLJ\n" +
            "5WH,C6D\n" +
            "52T,85V\n" +
            "754,CDL\n" +
            "K23,S8H\n" +
            "VXC,MBH\n" +
            "SJ7,5DJ\n" +
            "XGS,4JY\n" +
            "7H4,49Y\n" +
            "Q73,C57\n" +
            "HJJ,D55\n" +
            "HLB,39V\n" +
            "Y4D,378\n" +
            "LLT,GFJ\n" +
            "HB4,1FC\n" +
            "CRY,RS2\n" +
            "1K9,7KY\n" +
            "FW7,P2B\n" +
            "R9S,1QD\n" +
            "RHG,5G5\n" +
            "TPJ,K2K\n" +
            "7TF,LSH\n" +
            "ZTD,93G\n" +
            "S8Z,GWX\n" +
            "BG6,WS2\n" +
            "ZKH,NSP\n" +
            "YM2,F3G\n" +
            "65S,PX4\n" +
            "B32,D7C\n" +
            "GC4,B32\n" +
            "NRL,SAN\n" +
            "9ZM,NZR\n" +
            "SSM,XQK\n" +
            "2BY,VZ8\n" +
            "KTH,RSQ\n" +
            "KNL,4M3\n" +
            "BRB,3QT\n" +
            "FVQ,84F\n" +
            "3W9,HPK\n" +
            "K24,MR2\n" +
            "NCC,79G\n" +
            "Y63,NHN\n" +
            "VFD,RSB\n" +
            "24X,LKB\n" +
            "D4P,YM2\n" +
            "JZ1,JMC\n" +
            "BBH,4ZV\n" +
            "G3X,YSW\n" +
            "MD9,QCM\n" +
            "NSN,Q62\n" +
            "JRR,3SJ\n" +
            "SRD,9RV\n" +
            "B17,84L\n" +
            "C1J,9LC\n" +
            "356,QML\n" +
            "BV6,G74\n" +
            "8J9,LJG\n" +
            "1TP,GP4\n" +
            "3LR,Q7V\n" +
            "GPW,D96\n" +
            "YR7,9NZ\n" +
            "VKN,7W8\n" +
            "TWS,79M\n" +
            "D1X,B1X\n" +
            "XPZ,8G8\n" +
            "NSP,41B\n" +
            "KJ9,RGX\n" +
            "XFY,68S\n" +
            "QNH,JPX\n" +
            "YZ6,PJR\n" +
            "71J,MBC\n" +
            "74W,YZY\n" +
            "SSM,5HN\n" +
            "XPV,R92\n" +
            "8HH,2DS\n" +
            "LCP,YZR\n" +
            "3Q3,W1J\n" +
            "11M,KDG\n" +
            "X74,SGV\n" +
            "9XP,TRG\n" +
            "D55,P1F\n" +
            "WMC,1Z7\n" +
            "8HY,1M4\n" +
            "4NY,YM4\n" +
            "9KC,M8Q\n" +
            "R17,FLH\n" +
            "DGH,NFP\n" +
            "62P,H39\n" +
            "8Z6,82T\n" +
            "RP1,F3Q\n" +
            "NWX,8MP\n" +
            "SBY,LNW\n" +
            "LQ9,Y5W\n" +
            "9CL,YWJ\n" +
            "XY3,V99\n" +
            "FDZ,RPT\n" +
            "ZBL,3W9\n" +
            "R6Q,LJT\n" +
            "T3W,3FR\n" +
            "STB,962\n" +
            "D1D,6D8\n" +
            "J5Z,RWP\n" +
            "6BJ,5CQ\n" +
            "RKT,NJG\n" +
            "Q62,541\n" +
            "YT5,T5B\n" +
            "CN6,FXS\n" +
            "FJ6,7CB\n" +
            "44M,88Y\n" +
            "29Z,HM3\n" +
            "4ZV,12H\n" +
            "JN6,TSQ\n" +
            "NJW,L1Q\n" +
            "J29,X7L\n" +
            "TGZ,45Q\n" +
            "V7G,PGD\n" +
            "TFX,C5B\n" +
            "221,VDJ\n" +
            "5PF,FTF\n" +
            "H2K,F24\n" +
            "QWN,5CL\n" +
            "183,KQ5\n" +
            "PZF,9P9\n" +
            "YQ1,D79\n" +
            "Y88,FLQ\n" +
            "LVQ,8SP\n" +
            "MPM,K92\n" +
            "1GH,88V\n" +
            "6TR,6HP\n" +
            "Z6B,5JR\n" +
            "NHD,ZZD\n" +
            "LD3,NBQ\n" +
            "TJV,4QM\n" +
            "WH9,F8T\n" +
            "YJJ,BX1\n" +
            "L26,RXJ\n" +
            "NXG,BTY\n" +
            "6D8,X1L\n" +
            "D9K,TNS\n" +
            "3ZC,H33\n" +
            "TXW,VHN\n" +
            "GKJ,Z9L\n" +
            "V1B,FW7\n" +
            "71F,TX3\n" +
            "HYL,TVD\n" +
            "RQT,R36\n" +
            "YY6,K76\n" +
            "S88,QLH\n" +
            "SR7,2WR\n" +
            "NZQ,SD7\n" +
            "CBD,HDX\n" +
            "MJ5,4K9\n" +
            "LFL,F4D\n" +
            "HHC,4B6\n" +
            "GLJ,9CL\n" +
            "PFN,ZBL\n" +
            "5CQ,J6W\n" +
            "XQM,JRC\n" +
            "GS8,4MR\n" +
            "VDJ,68L\n" +
            "69M,R7V\n" +
            "VZ3,ZSZ\n" +
            "2JL,B1J\n" +
            "JSZ,DPR\n" +
            "Q21,39N\n" +
            "SGW,31R\n" +
            "36P,X9P\n" +
            "B17,5FG\n" +
            "2NY,FQ2\n" +
            "6FS,HMH\n" +
            "GH1,CSK\n" +
            "7V7,5WH\n" +
            "6KD,DD2\n" +
            "LWK,DCQ\n" +
            "88V,MD9\n" +
            "4RC,DG7\n" +
            "4N9,34L\n" +
            "81Q,VQ2\n" +
            "P3D,7L3\n" +
            "6CV,DRB\n" +
            "VT2,GWT\n" +
            "YVS,HJJ\n" +
            "XJS,D8K\n" +
            "X1L,LKS\n" +
            "ZVC,4SX\n" +
            "39V,4QT\n" +
            "R47,MKH\n" +
            "B1X,XTL\n" +
            "47R,36P\n" +
            "FTZ,K8B\n" +
            "CS3,5GX\n" +
            "DCG,8WN\n" +
            "DWF,G4X\n" +
            "VP4,CGS\n" +
            "PTS,PV4\n" +
            "J6Y,1TJ\n" +
            "6WY,Z2H\n" +
            "B7T,5P5\n" +
            "Q5R,NSX\n" +
            "GRS,CJX\n" +
            "HPM,1S9\n" +
            "KDG,KB8\n" +
            "N2D,J16\n" +
            "LKQ,C5G\n" +
            "YWJ,ZMC\n" +
            "9YB,PQD\n" +
            "ZX3,BCR\n" +
            "31R,37J\n" +
            "X68,KL6\n" +
            "8SV,BZ6\n" +
            "LJT,5NF\n" +
            "NGQ,C7M\n" +
            "83G,356\n" +
            "YFC,F7Q\n" +
            "H4B,LLL\n" +
            "SWK,RQD\n" +
            "66Y,6NW\n" +
            "8LW,GC4\n" +
            "664,33L\n" +
            "WJF,JBV\n" +
            "RWP,VP4\n" +
            "6N8,4NY\n" +
            "8HH,Z96\n" +
            "32Y,4TN\n" +
            "6SD,MRH\n" +
            "667,JXJ\n" +
            "P56,K1S\n" +
            "J6H,JNC\n" +
            "YGQ,7MZ\n" +
            "D5J,RGP\n" +
            "5KQ,X74\n" +
            "D79,ZX3\n" +
            "NBQ,XGG\n" +
            "RHH,N4P\n" +
            "ZGQ,T3Y\n" +
            "5RN,YQH\n" +
            "X5M,PNP\n" +
            "71F,HS6\n" +
            "LKV,YR7\n" +
            "S16,FPM\n" +
            "B1B,LZ4\n" +
            "N1C,Q32\n" +
            "BTS,BBX\n" +
            "WMC,B3X\n" +
            "LSN,12X\n" +
            "7L3,6CP\n" +
            "R7V,Y7F\n" +
            "ZDC,H67\n" +
            "BDV,HPL\n" +
            "W1J,7LH\n" +
            "4KY,DSQ\n" +
            "KQF,184\n" +
            "9SJ,27M\n" +
            "PZ5,STC\n" +
            "X7L,C8P\n" +
            "BFR,8T4\n" +
            "DM6,HRQ\n" +
            "GVN,74S\n" +
            "RWH,V7W\n" +
            "CJX,TM7\n" +
            "NT4,HT2\n" +
            "5DN,132\n" +
            "Y49,C1H\n" +
            "8K2,54Z\n" +
            "ZWF,H9J\n" +
            "N5M,NXG\n" +
            "769,GPW\n" +
            "Q2L,DR9\n" +
            "X4N,QNM\n" +
            "3GL,B7T\n" +
            "8PW,5XV\n" +
            "37J,PL7\n" +
            "C1H,PZN\n" +
            "PZX,VKH\n" +
            "RF2,B1D\n" +
            "HT2,X29\n" +
            "SG2,65Y\n" +
            "VJ3,DTW\n" +
            "P51,HMY\n" +
            "FTL,V1F\n" +
            "N2S,9P2\n" +
            "455,5TL\n" +
            "JL2,RVD\n" +
            "GW5,H9M\n" +
            "VHN,TM9\n" +
            "C6D,VFD\n" +
            "GBC,MWX\n" +
            "DV7,TF5\n" +
            "WGL,VNF\n" +
            "WJ6,BBH\n" +
            "PXG,CDB\n" +
            "ZWK,5CF\n" +
            "BSH,26D\n" +
            "2T8,RHH\n" +
            "33L,JCD\n" +
            "LXH,1TZ\n" +
            "X9P,5W6\n" +
            "FLZ,74Y\n" +
            "NT7,2HF\n" +
            "P4Z,PYC\n" +
            "DLZ,WJ6\n" +
            "TPB,KZT\n" +
            "MD7,FJ2\n" +
            "14T,4DW\n" +
            "ZB1,698\n" +
            "F4D,79F\n" +
            "LNW,MYF\n" +
            "JRW,6XM\n" +
            "ZVW,MFZ\n" +
            "CDW,4VF\n" +
            "1WN,NH2\n" +
            "QHY,YLM\n" +
            "XFK,3V1\n" +
            "DLJ,LFD\n" +
            "SGH,89K\n" +
            "N7L,F44\n" +
            "7QH,HPM\n" +
            "SLR,QNH\n" +
            "ZQF,9SS\n" +
            "VKH,9GQ\n" +
            "5GX,2TG\n" +
            "WS2,2QF\n" +
            "R6R,RDZ\n" +
            "132,8RP\n" +
            "D1T,29D\n" +
            "SGW,4WJ\n" +
            "ZVF,WPH\n" +
            "RKN,R6Q\n" +
            "T2M,PKK\n" +
            "HDR,71Q\n" +
            "5BQ,Y49\n" +
            "962,QHP\n" +
            "NXG,LBC\n" +
            "FLQ,8HY\n" +
            "39N,WWX\n" +
            "XKN,HDR\n" +
            "VDR,958\n" +
            "K43,66N\n" +
            "FGZ,Q2P\n" +
            "RS2,D42\n" +
            "8X5,WZZ\n" +
            "3NN,8K2\n" +
            "B39,GGY\n" +
            "G9B,J6H\n" +
            "8SN,138\n" +
            "KPC,FY9\n" +
            "PVX,TFS\n" +
            "G81,S16\n" +
            "BWR,QJ5\n" +
            "TM9,5K6\n" +
            "33G,DDQ\n" +
            "TTN,7V7\n" +
            "9P2,9CG\n" +
            "7HW,B84\n" +
            "5DC,YNL\n" +
            "PMC,LKP\n" +
            "CRY,G85\n" +
            "P65,6BJ\n" +
            "9CS,TBX\n" +
            "LHP,5QG\n" +
            "KLY,BR2\n" +
            "HCB,Z15\n" +
            "X77,KPR\n" +
            "KSC,W6S\n" +
            "964,TSH\n" +
            "8RP,1V8\n" +
            "9FM,2NY\n" +
            "BYF,MBY\n" +
            "LD9,FSQ\n" +
            "3XR,33S\n" +
            "9PJ,8Z4\n" +
            "N3X,3WN\n" +
            "8NM,NHD\n" +
            "MYF,M7C\n" +
            "F3Q,221\n" +
            "N7L,KNP\n" +
            "C5N,6TR\n" +
            "71M,J84\n" +
            "97V,TPJ\n" +
            "CWF,9QV\n" +
            "5DC,HCZ\n" +
            "VP6,17S\n" +
            "CMC,KTM\n" +
            "356,N4M\n" +
            "DTW,VY7\n" +
            "X3S,F1H\n" +
            "RHL,9Y9";
}
